/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as PayReferenceRouteImport } from './routes/pay.$reference'
import { Route as OOrderIdRouteImport } from './routes/o.$orderId'
import { Route as DashboardCatalogRouteImport } from './routes/dashboard.catalog'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard.settings.index'
import { Route as PayReferenceSuccessRouteImport } from './routes/pay.$reference.success'
import { Route as DashboardSettingsPayoutsRouteImport } from './routes/dashboard.settings.payouts'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack.webhook'
import { Route as ApiPublicPayReferenceInitRouteImport } from './routes/api/public/pay.$reference.init'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PayReferenceRoute = PayReferenceRouteImport.update({
  id: '/pay/$reference',
  path: '/pay/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const OOrderIdRoute = OOrderIdRouteImport.update({
  id: '/o/$orderId',
  path: '/o/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCatalogRoute = DashboardCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const PayReferenceSuccessRoute = PayReferenceSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => PayReferenceRoute,
} as any)
const DashboardSettingsPayoutsRoute =
  DashboardSettingsPayoutsRouteImport.update({
    id: '/settings/payouts',
    path: '/settings/payouts',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack/webhook',
    path: '/api/public/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPayReferenceInitRoute =
  ApiPublicPayReferenceInitRouteImport.update({
    id: '/api/public/pay/$reference/init',
    path: '/api/public/pay/$reference/init',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/o/$orderId': typeof OOrderIdRoute
  '/pay/$reference': typeof PayReferenceRouteWithChildren
  '/s/$slug': typeof SSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/payouts': typeof DashboardSettingsPayoutsRoute
  '/pay/$reference/success': typeof PayReferenceSuccessRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/pay/$reference/init': typeof ApiPublicPayReferenceInitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/o/$orderId': typeof OOrderIdRoute
  '/pay/$reference': typeof PayReferenceRouteWithChildren
  '/s/$slug': typeof SSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/settings/payouts': typeof DashboardSettingsPayoutsRoute
  '/pay/$reference/success': typeof PayReferenceSuccessRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/pay/$reference/init': typeof ApiPublicPayReferenceInitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/o/$orderId': typeof OOrderIdRoute
  '/pay/$reference': typeof PayReferenceRouteWithChildren
  '/s/$slug': typeof SSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/payouts': typeof DashboardSettingsPayoutsRoute
  '/pay/$reference/success': typeof PayReferenceSuccessRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/pay/$reference/init': typeof ApiPublicPayReferenceInitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/dashboard/analytics'
    | '/dashboard/catalog'
    | '/o/$orderId'
    | '/pay/$reference'
    | '/s/$slug'
    | '/dashboard/'
    | '/dashboard/settings/payouts'
    | '/pay/$reference/success'
    | '/dashboard/settings/'
    | '/api/public/paystack/webhook'
    | '/api/public/pay/$reference/init'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/dashboard/analytics'
    | '/dashboard/catalog'
    | '/o/$orderId'
    | '/pay/$reference'
    | '/s/$slug'
    | '/dashboard'
    | '/dashboard/settings/payouts'
    | '/pay/$reference/success'
    | '/dashboard/settings'
    | '/api/public/paystack/webhook'
    | '/api/public/pay/$reference/init'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/dashboard/analytics'
    | '/dashboard/catalog'
    | '/o/$orderId'
    | '/pay/$reference'
    | '/s/$slug'
    | '/dashboard/'
    | '/dashboard/settings/payouts'
    | '/pay/$reference/success'
    | '/dashboard/settings/'
    | '/api/public/paystack/webhook'
    | '/api/public/pay/$reference/init'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  OOrderIdRoute: typeof OOrderIdRoute
  PayReferenceRoute: typeof PayReferenceRouteWithChildren
  SSlugRoute: typeof SSlugRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicPayReferenceInitRoute: typeof ApiPublicPayReferenceInitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$reference': {
      id: '/pay/$reference'
      path: '/pay/$reference'
      fullPath: '/pay/$reference'
      preLoaderRoute: typeof PayReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$orderId': {
      id: '/o/$orderId'
      path: '/o/$orderId'
      fullPath: '/o/$orderId'
      preLoaderRoute: typeof OOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/catalog': {
      id: '/dashboard/catalog'
      path: '/catalog'
      fullPath: '/dashboard/catalog'
      preLoaderRoute: typeof DashboardCatalogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/pay/$reference/success': {
      id: '/pay/$reference/success'
      path: '/success'
      fullPath: '/pay/$reference/success'
      preLoaderRoute: typeof PayReferenceSuccessRouteImport
      parentRoute: typeof PayReferenceRoute
    }
    '/dashboard/settings/payouts': {
      id: '/dashboard/settings/payouts'
      path: '/settings/payouts'
      fullPath: '/dashboard/settings/payouts'
      preLoaderRoute: typeof DashboardSettingsPayoutsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/paystack/webhook': {
      id: '/api/public/paystack/webhook'
      path: '/api/public/paystack/webhook'
      fullPath: '/api/public/paystack/webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pay/$reference/init': {
      id: '/api/public/pay/$reference/init'
      path: '/api/public/pay/$reference/init'
      fullPath: '/api/public/pay/$reference/init'
      preLoaderRoute: typeof ApiPublicPayReferenceInitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCatalogRoute: typeof DashboardCatalogRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSettingsPayoutsRoute: typeof DashboardSettingsPayoutsRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCatalogRoute: DashboardCatalogRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsPayoutsRoute: DashboardSettingsPayoutsRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PayReferenceRouteChildren {
  PayReferenceSuccessRoute: typeof PayReferenceSuccessRoute
}

const PayReferenceRouteChildren: PayReferenceRouteChildren = {
  PayReferenceSuccessRoute: PayReferenceSuccessRoute,
}

const PayReferenceRouteWithChildren = PayReferenceRoute._addFileChildren(
  PayReferenceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  OOrderIdRoute: OOrderIdRoute,
  PayReferenceRoute: PayReferenceRouteWithChildren,
  SSlugRoute: SSlugRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicPayReferenceInitRoute: ApiPublicPayReferenceInitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
